### ISSUE TITLE
The last version (10.2.1) lack lib directory by npm repository!

### ISSUE THREAD

**Issue by tony2y** [nikku/didi#35]
<img width="841" alt="image" src="https://github.com/nikku/didi/assets/38598582/72e00070-3b51-4ef2-b4f2-9e97cb046c65">

**Comment by tony2y** [comment]
@nikku

**Comment by nikku** [comment]
@tony2y This is an absolute fine setup for a package. The `package#json#exports` field defines exports that will be used. For a long time we only published `dist` folder: https://github.com/nikku/didi/commit/71c38d49266e1fbf6e3399a80858b6492e7dc17c.

**Comment by tony2y** [comment]
![image](https://github.com/nikku/didi/assets/38598582/3dfaa2c8-8d23-4bc0-8c9b-2d2436cfd78d)
But now there is an issue that when using diagram js in the Vue project, executing npm run dev will result in errors。

**Comment by tony2y** [comment]
<img width="969" alt="image" src="https://github.com/nikku/didi/assets/38598582/5630c99f-9bb6-4ebb-9553-d6c14858f79b">

**Comment by tony2y** [comment]
@nikku

**Comment by nikku** [comment]
@tony2y The issue is that you use an [unsupported and outdated](https://nodejs.github.io/nodejs.dev/en/about/releases/) node version. Node 18 is in maintainance, and the didi baseline is [node >= 16](https://github.com/nikku/didi/blob/main/package.json#L39). Upon installing you should see a warning.

**Comment by tony2y** [comment]
Thank you for your answer！！
